language: python

python:
  - 2.6
  - 2.7
  - pypy

before_install:
  - sudo service elasticsearch start
  - sleep 3

install:
  - pip install -e .
  - pip install simplejson

script: python setup.py test
